<?php

declare(strict_types=1);

/**
 * @file
 * Provides a passive entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function passive_theme(): array {
  return [
    'passive' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for passive templates.
 *
 * Default template: passive.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the passive information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_passive(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function passive_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish passives.
      $storage = \Drupal::entityTypeManager()->getStorage('passive');
      $passive_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($passive_ids) as $passive) {
        $passive->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize passives.
      $storage = \Drupal::entityTypeManager()->getStorage('passive');
      $passive_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($passive_ids) as $passive) {
        $passive->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function passive_user_predelete(UserInterface $account): void {
  // Delete passives that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('passive');
  $passive_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($passive_ids)
  );
}
